### ISSUE TITLE
breaking: Adopt C# coding conventions

### ISSUE THREAD

**Issue by paulpach** [MirrorNG/MirrorNG#1]
This will require changes in your game.

Official conventions can be found here: 

The goal of this feature is to adopt official [c# coding conventions](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions).  A good summary can be found [here](https://www.dofactory.com/reference/csharp-coding-standards):

The goal is consistency,  any code that does not adhere to these convention is to be considered a defect.

Some things where Mirror violate conventions include
* use var when type is obvious from right hand side
* use PascalCase for public fields and properties

This is a very easy way to get started,  find a public field that violates the convention and open a pull request.

**Comment by toreau** [comment]
I will try to adhere to these rules, even though I don't agree with SCREAMING_CONSTANTS. The one thing that confuses me the most is this:

* I prefer using `private` in front of private methods, even though it's not necessary.
* I prefer naming variables lowerCased for private variables, not using an underscore. But using an underscore is actually a bit tempting.

**Comment by paulpach** [comment]
tracking in separate things
