### ISSUE TITLE
isClient & isServer always false in OnDestroy()

### ISSUE THREAD

**Issue by Lymdun** [MirrorNG/MirrorNG#130]
Confirmed on hostmode, not in server only mode.

**Comment by uweenukr** [comment]
OnDestroy for what?

**Comment by Lymdun** [comment]
On any network behaviour

**Comment by uweenukr** [comment]
I tested this with a debug at the start of OnDestroy() and with the Tanks and Additive examples I was unable to reproduce the issue. Each time IsServer was true at the time the destroy was called. Can you provide a repro or more details? I want to help find this for you :)

**Comment by paulpach** [comment]
This is the intended behavior now.   
The object is unspawned before it is destroyed,  so naturally it won't be IsServer anymore by the time OnDestroy is called.

If you want to do some cleanup before it is unspawned subscribe to OnStopServer event
