### ISSUE TITLE
MirrorNG meets OpenUPM

### ISSUE THREAD

**Issue by favoyang** [MirrorNG/MirrorNG#18]
**Please explain the suggested feature in detail.**

Hi @paulpach,

I have followed a few threads on the upstream repo, then I found your MirrorNG fork. A great move! I'm the creator of [OpenUPM](https://openupm.com), a public upm registry with automatic build pipelines that publish new package bundle based on valid git tags. You can read the announcement on [medium](https://medium.com/openupm/openupm-beta-is-now-available-a6665ff60c71) to get the basic idea, so far it hosts 100+ packages as of Jan 2020.

UPM offering better version and dependency management, is the future to delivery reusable component in the Unity Engine. I have added [your work to the platform](https://openupm.com/packages/com.mirrorng.mirrorng/). To make it useful, could you please create a GitHub release 4.0.0 _from the upm branch_?

Or maybe to make the version string different enough from the original mirror project, try out something bigger than 6.x.y? I will suggest a pattern like mirror: x.y.z => mirrorng: 1x.y.z, i.e. 6.x.y => 16.x.y

Thought?

**Comment by paulpach** [comment]
@favoyang thanks.   yes,  versioning is on the way.  I will use sematic versioning with UPM,  it will take some time to set up.

**Comment by favoyang** [comment]
Though the platform can handle any directory structure (package.json position). Tag from the upm branch is recommended.

**Comment by paulpach** [comment]
Done in #24

**Comment by paulpach** [comment]
Does not seem to work:
```
$ openupm search mirrorng                                                                                                                                         20:48:53
fast search endpoint is not available, using old search.
No matches found for "mirrorng"
```

**Comment by favoyang** [comment]
I'm checking it now.

**Comment by favoyang** [comment]
Sorry for the issue, it's been fixed manually. I will find the reason behind later then.

**Comment by favoyang** [comment]
The package can be successfully installed via the openupm-cli
```
$ openupm add com.mirrorng.mirrorng
added: com.mirrorng.mirrorng@1.3.0
manifest updated, please open unity project to apply changes
```

![image](https://user-images.githubusercontent.com/125390/71759851-bf039a80-2eee-11ea-8bbb-7c2366eca00b.png)

But I find a few compile errors for the Examples folder
```
Library\PackageCache\com.mirrorng.mirrorng@1.3.0\Examples\Room\Scripts\NetworkRoomManagerExt.cs(6,42): error CS0246: The type or namespace name 'NetworkRoomManager' could not be found (are you missing a using directive or an assembly reference?)
```

Is this an optional thing? (i.e. to demo the integration with 3rd party library).

A typical solution would be be moving the Samples tot Samples~ folder. The folder with `~` is not get compiled by default. But it make the package development hard. You/me have a few choices
- The openupm build pipeline can solve it magically, by moving the Samples list in the package.json to Samples~ folder (not implemented yet)
- The openupm build pipeline can support a `npm prepare / build` command, so you can do the some hooks. Notice that openupm build pipeline is running in a linux box.
- There's a tip to [use soft link](https://forum.unity.com/threads/samples-in-packages-manual-setup.623080/), by actually placing code into the Samples~ folder, but create a symbolic link to Samples and ignore the Samples folder.

Your opinion?

**Comment by favoyang** [comment]
Another question, who publish the 1.3.0 branch? I checked the github workflow and the [.releaserc.yml](https://github.com/MirrorNG/MirrorNG/blob/master/.releaserc.yml), but it seems only publish the x.y.z-master tag.

**Comment by paulpach** [comment]
@favoyang still fixing the last issue of versioning,  first actual release will be 1.0.0
There will be 2 tags per release  

* 1.0.0-master   is a tag on the master branch
* 1.0.0  is the tag on upm branch.

The examples will be fixed too.

**Comment by paulpach** [comment]
Fixed,  version 1.0.0 is out,  it is the very first one.   

openupm search is still reporting 1.3.0

How often does openupm update it's package list?   there will be lots of releases in MirrorNG,  every feature, every fix will trigger a release  (refactors and documentation do not).

**Comment by favoyang** [comment]
1) I didn't see any tags/releases? https://github.com/MirrorNG/MirrorNG/tags
![image](https://user-images.githubusercontent.com/125390/71769452-84d0e200-2f5c-11ea-9fba-e03a148d7aa6.png)

2) openupm, behavior similar to npm that it can not override/unpublish published content. (didn't like git, you can delete your tags back and forth). That's why it returns 1.3.0 the latest successfully built version. But for your case I delete all of them.

you need run this once in your shell
```
rm ~/.openupm/com.openupm.all.json
```

Now nothing published here
```
$ openupm search com.mirrorng.mirrorng
fast search endpoint is not available, using old search.
No matches found for "com.mirrorng.mirrorng"
```

Next time if you messy something in a release, you will have to bump the version to create a new release to fix it.

**Comment by favoyang** [comment]
3. the build pipeline scans every every 5 mins, the build bot run 1 min per release. So package publishing typically in the range of 1~6 mins since your GitHub release, from just been put into the build queue to wait a full cycle.

    You can watch the https://openupm.com/packages/com.mirrorng.mirrorng/ build issues section (need some manually refreshes) to get the build results. In your case all -master suffix tags will fail (as expected) and others shall succeed. 

![image](https://user-images.githubusercontent.com/125390/71769667-cb274080-2f5e-11ea-9103-1fe19a586cdb.png)

An example of working package
![image](https://user-images.githubusercontent.com/125390/71769674-f01bb380-2f5e-11ea-8fd7-2c28729589c3.png)

**Comment by favoyang** [comment]
4. Thanks for fixing the Sample folder.
5. Sorry for letting you go through many issues during the publishing. Usually I deal with repository with existing upm branch and releases, that makes things a lot smooth. 

For the timezone issue, I will follow this thread about 8 hours later.

**Comment by paulpach** [comment]
@favoyang 
The changes are needed whether I support openupm or not,  so you are not making me work any harder.

I am very close to have that 1.0.0 tag fully automated and stable,  minor issue still remains.  Once 1.0.0 then the dust is settled,  I won't be deleting tags anymore,  don't worry.

**Comment by paulpach** [comment]
fixed,  everything appears to be working now.

**Comment by favoyang** [comment]
Looks good. added https://github.com/MirrorNG/MirrorNG/pull/30 for badges.
