### ISSUE TITLE
breaking: Remove singletons

### ISSUE THREAD

**Issue by paulpach** [MirrorNG/MirrorNG#2]
Singletons are a terrible antipattern. Some good articles are here:
https://www.dotnetcurry.com/patterns-practices/1350/singleton-design-anti-pattern-csharp
https://blogs.msdn.microsoft.com/scottdensmore/2004/05/25/why-singletons-are-evil/

The goal of this project is to **remove all singletons**,   every singleton will be considered a design defect.   You can help by opening an issue for every singleton you find

**Comment by Lymdun** [comment]
Removal of NetworkClient singleton: https://github.com/vis2k/Mirror/pull/1372

**Comment by paulpach** [comment]
tracking in individual issues
