### ISSUE TITLE
Hidden exception is being thrown if local player object has owned objects when closing server

### ISSUE THREAD

**Issue by Hertzole** [MirrorNG/MirrorNG#225]
**Describe the bug**
If your local player object (that's spawned by the PlayerSpawner script) is spawning objects that have the local player as the owner and the server stops, a hidden NullReferenceException is being thrown in the `DestroyOwnedObjects` method in the `NetworkConnection` class. It seems to be because it's destroying itself first and calling the Reset method on itself before destroying the child objects. This causes the Identity.Server property to be null, thus causing the NullReferenceException.

The NullReferenceException is also being thrown silently. It is never shown (probably due to Async methods), so a way to bring them forward to the main thread probably wouldn't hurt, in case something goes wrong.

Due to this, the rest of the code isn't being called in the `NetworkServer.OnDisconnected` method. That means the LocalConnection isn't being reset and this stops you from properly hosting another server.

**Repro project**
[Mirror Hosting Bug.zip](https://github.com/MirrorNG/MirrorNG/files/4781316/Mirror.Hosting.Bug.zip)

**To Reproduce**
1. Open the attached project that you can get above.
2. Go into Scenes/SampleScene.scene
3. Enter play mode and start hosting. Notice how the prefab 'Network Player' is being spawned.
4. Right after stop hosting and then try again. Notice how this time it isn't being spawned. That's because the server hasn't been started properly, as mentioned above. 

**Expected behavior**
Every object is destroyed properly and that you can start hosting again.

**Desktop (please complete the following information):**
* OS: Windows 64-bit
* Build target: Windows 64-bit
* Unity version: 2020.1b12
* Mirror branch: master

**Comment by uweenukr** [comment]
Can you verify if this is still an issue? Alot of related changes have happened since it was reported.

**Comment by Hertzole** [comment]
Sorry for the delay.
This is still an issue. If you just do a simple `Debug.Log(clientOwnedObjects.Contains(Identity));` in the `DestroyOwnedObjects` method in `NetworkConnection` it still exists in the same list it's destroying and thus destroys itself before any of the children.

**Comment by uweenukr** [comment]
Can you check this again? There was a race condition identified and fixed recently.

**Comment by Hertzole** [comment]
It's still a problem. I've attached a new project to reproduce the issue. It has a slight change to Mirror with a Deubg.Log message in the NetworkConnection class saying what it _should_ destroy and what it did destroy. Just like before, it destroys itself, the Identity, first and then tries to use the Identity to destroy the other objects. 

To test the project, just open it up (I used 2020.2b4 but I don't think it matters too much) and go to Scenes/SampleScene and play.
Then when you press host, you should see "Player Controller" spawn into the scene (a simple cube), now disconnect (this also logs the debug messages I mentioned above) and try to host again. This time the player controller object does not spawn.
[Mirror Hosting Bug.zip](https://github.com/MirrorNG/MirrorNG/files/5306435/Mirror.Hosting.Bug.zip)

**Comment by Hertzole** [comment]
I've made a PR with one way to fix this issue. One could consider it as a bit dirty but it gets the work done. #373

**Comment by uweenukr** [comment]
I tried writing a test to make this fail

![image](https://user-images.githubusercontent.com/1385108/94929343-f5c50c00-0492-11eb-839e-43dbb6e90d5e.png)

and also adding this for good measure

![image](https://user-images.githubusercontent.com/1385108/94929380-05445500-0493-11eb-80b2-4d1e7f27dd53.png)


Cant get it to fail
