### ISSUE TITLE
Server | Client On NetIdentities Null

### ISSUE THREAD

**Issue by dragonslaya84** [MirrorNG/MirrorNG#344]
We use the netidentity.start and netidentity.client to register for listener's in onenable. This causes alot of headache at times its fine other times it is not. I do have a static manager for network manager so its easily resolved for me because server and client variables on the networkmanager are set up before anything else.

I use object pooling so I must disable and enable objects on the fly with it and I need to know when it starts up on server or client to setup different data and this causes issues because 4/10 the client and server variable under netidentity has not been setup. 

I have not had chance look at code yet to know when mirrorng setups these variables but will do so. Placing this here for future people until this can be resolved. The variables should be populated on awake or start before enable gets fired.

**Comment by uweenukr** [comment]
seems like this is the same issue as #330?
