### ISSUE TITLE
Server Event Listener's

### ISSUE THREAD

**Issue by dragonslaya84** [MirrorNG/MirrorNG#345]
**Describe the bug**
I have gotten messages and d/c issues for a script that attaches itself to netidentity.server.onstart. The script itself is a server command label with [Server] above the method. The method it hand on my side is registered to a listener of health change event. Both server and client register to this on my end. I placed a if(!IsServer) check before the netidentity.server.OnstartServer listener and it solved the issue.

**Expected behavior**
I expected that if i am registering to a listener for server that it only ever will get fired on the server. But current behavior tells me that this also fires on the client when client receives a message that he has started up on server or something?

**Comment by uweenukr** [comment]
Reviewing the code I am not sure where this comes from. The existing test fixtures dont provide proper timing so before I wrote a whole new one I did a manual test. I set a breakpoint on StartServer and ran Tanks example with client only in the editor. The breakpoint never hit.

**Comment by paulpach** [comment]
This may have been fixed already,  I recently rewrote where the StartServer gets called,  I don't show how this is possible anymore.
