### ISSUE TITLE
Compile errors due to missing meta file

### ISSUE THREAD

**Issue by johanhelsing** [MirrorNG/MirrorNG#396]
After installing the package with open upm I get this error:

![image](https://user-images.githubusercontent.com/2620557/96149590-cc33c800-0f09-11eb-83c5-9b6611ffe3f4.png)

Which seems to be causing compilation errors.

**Comment by Lymdun** [comment]
https://github.com/MirrorNG/MirrorNG/commit/de24dc4dee7279b299642732286d7cc4273692e5
Will be fixed on next release

**Comment by paulpach** [comment]
fixed
