### ISSUE TITLE
ServerObjectManager fails to instantiate prefabs on client

### ISSUE THREAD

**Issue by OneFirefly** [MirrorNG/MirrorNG#470]
**Describe the bug**
Upgrading my project to v56.3.4 I had to replace Server.Spawn etc with serverObjectManager.Spawn etc
After doing that I noticed on a remote client (server in host mode) the prefabs don't show up as GameObjects (also not shown in Hierarchy).
There were no errors and no related warnings as usually expected.

**My Code**
In my project multiple Spawn commands didn't seem to have any effect on the client.
- one Spawn called by NetworkServer.Authenticated UnityEvent
- and the other inside Update loop
I hope you can make sure both cases work properly

**Additional info**
It is possible I didn't have the _Spawn Prefabs_ referenced. I noticed those were deleted when I reverted to a version before ServerObjectManager was introduced. So perhaps v56.3.4 failed to show related errors/warnings. (possible bug)
After reverting everything and adding the Spawn Prefabs everything worked properly again.

In case the _Spawn Prefabs_ were referenced then the bug is that the prefabs weren't instantiated on the remote client.

**Comment by OneFirefly** [comment]
The problem here was that I didn't create and reference a _ClientObjectManager_ component and there was no error shown because of that.
Please before you close this ticket: make it so an error shows if someone forgets to reference PlayerSpawner's _ClientObjectManager_, or spawning will silently fail.

**Comment by uweenukr** [comment]
Adding an exception/error via #472 .

**Comment by phodoval** [comment]
@OneFirefly Can we close this one now?
