### ISSUE TITLE
Server doesn't work after re-entering play mode with Fast Domain Reload

### ISSUE THREAD

**Issue by Jobus0** [MirrorNG/MirrorNG#547]
**Describe the bug**
After hosting the server, disconnecting, exiting play mode, and then entering play mode again, the server fails to work correctly again until a domain reload has been triggered or editor is restarted.

While broken, Server.Active will go true, but PlayerSpawner does not spawn the player, and after disconnecting again, Server.Active will incorrectly stay true.

I've tried with Kcp, IgnoranceNG, and Websocket. The bug happens to the first two, but not to Websocket. From what I can tell, the bug is identical between Kcp and IgnoranceNG. However, if one triggers the bug with either of those two, and then switches to Websocket, then it will also be broken. But Websocket never triggers the bug itself.

**Repro project**
[MirrorNG Test.zip](https://github.com/MirrorNG/MirrorNG/files/5863077/MirrorNG.Test.zip)

Simple project with three scenes (based on Mirror's "Basic" example), one for each transport, but otherwise identical.

**To Reproduce**
1. Open the attached project.
2. Open the "Kcp" scene.
3. Enter play mode.
4. Click "Start Host" button and notice "Server Active: True" and the "Player 01" UI element.
5. Click "Stop Network" and notice "Server Active: False".
6. Exit and re-enter play mode.
7. Click "Start Host" button and notice "Server Active: True", but no "Player 01".
8. Click "Stop Network" and notice "Server Active" is still "True".

**Expected behavior**
Starting host should spawn a player every time, and stopping network should set "Server Active" to False every time.

**Desktop (please complete the following information):**
* OS: Windows 10
* Build target: Editor
* Unity version: 2020.1.16

**Comment by paulpach** [comment]
I downloaded the sample project, but it does not have a scene

**Comment by Jobus0** [comment]
In the .zip there are Websocket.unity, Kcp.unity and IgnoranceNG.unity. Do those not load in the editor for you? They're in the Assets folder root.
